<Command>
    size_hint_y: None
    pos_hint: {"right": .98}
    height: self.texture_size[1]
    padding: 12, 10
    theme_color: "Custom"
    text_color: 1, 1, 1, 1
    canvas.before:
        Color:
            rgb: (1, 1, 1, 1)
        RoundedRectangle:
            size: self.width, self.height
            pos: self.pos
            radius: [23, 23, 0, 23]

<Response>
    size_hint_y: None
    pos_hint: {"x": .02}
    height: self.texture_size[1]
    padding: 12, 10
    theme_color: "Custom"
    text_color: 1, 1, 1, 1
    canvas.before:
        Color:
            rgb: (1, 1, 1, 1)
        RoundedRectangle:
            size: self.width, self.height
            pos: self.pos
            radius: [23, 23, 23, 0]

MDScreen:
    text_input: text_input
    user_name: user_name
    state: state
    chat_list: chat_list
    name: 'GPT'

    FitImage:
        source: 'background.png'

    MDFloatLayout:
        MDFloatLayout:
            md_bg_color: 5/255, 5/255, 5/255, 15/255
            size_hint_y: .11
            pos_hint: {"center_y": .95}
            radius: [0, 0, 20, 20]

            MDLabel:
                id: user_name
                text: "Chat GPT"
                pos_hint: {"center_y": .5}
                halign: "center"
                font_name: "MontSem"
                font_size: "24sp"

            MDLabel:
                id: state
                text: "Online"
                pos_hint: {"center_y": .2}
                halign: "center"
                font_name: "MontReg"
                font_size: "11sp"

            MDIconButton:
                icon: "back_l.png"
                icon_size: "16sp"
                pos_hint: {"center_x": .88, "center_y": .50}
                user_font_size: "22sp"
                theme_text_color: "Custom"
                text_color: 1, 1, 1, 1
                on_release: 
                    root.manager.transition.direction = "left"
                    root.manager.current = "trans"

        ScrollView:
            size_hint_y: .77
            pos_hint: {"x": .0, "y": .116}
            do_scroll_x: False
            do_scroll_y: True
            BoxLayout:
                id: chat_list
                orientation: "vertical"
                size: (root.width, root.height)
                height: self.minimum_height
                size_hint: None, None
                pos_hint: {'top': 10}
                cols: 1
                spacing: 5

    MDFloatLayout:
        md_bg_color: 5/255, 5/255, 5/255, 15/255
        size_hint_y: .11

        MDFloatLayout:
            size_hint: .7, .55
            pos_hint: {"center_x": .5, "center_y": .5} 
            canvas:
                Color:
                    rgb: (1, 1, 1, 1)
                
                RoundedRectangle:
                    size: self.size
                    pos: self.pos 
                    radius: [23, 23, 23, 23]
            
            TextInput:
                id: text_input
                hint_text: "Type your message..."
                size_hint: 1, None
                pos_hint: {"center_x": .5, "center_y": .5}
                font_size: "18sp"
                height: self.minimum_height
                cursor_color: 30/255, 144/255, 1, 1
                multiline: False
                cursor_width: "2sp"
                foreground_color: 0, 0, 0, 1
                background_color: 0, 0, 0, 0
                padding: 15
                font_name: "MontReg"

        MDIconButton:
            icon: "send"
            icon_size: "16sp"
            pos_hint: {"center_x": .92, "center_y": .5}
            user_font_size: "22sp"
            theme_text_color: "Custom"
            text_color: 1, 1, 1, 1
            md_bg_color: 30/255, 144/255, 1, 1
            on_release: app.chat_control.send_gpt()

        MDIconButton:
            icon: "add.png"
            pos_hint: {"center_x": .1,"center_y": .5}
            user_font_size: "22sp"
            theme_text_color: "Custom"
            text_color: 1, 1, 1, 1
            md_bg_color: 0, 0, 0, 0
            on_release: app.chat_control.add()
